name: On Push Run
on: [push]
jobs:
  check-shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
        - run: shell list.sh
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@<action version> # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
